function [C2_max, C3_max, C4_max, C2_min, C3_min, C4_min] = find_g_min_max(col_name, sub_struct,t_C2max_cl, t_C3max_cl, t_C4max_cl, t_C2min_cl, t_C3min_cl,  t_C4min_cl)
    texmax_C2 = max([sub_struct.(col_name).C2(:).MeanIntensity]);
    texmax_C3 = max([sub_struct.(col_name).C3(:).MeanIntensity]);
    texmax_C4 = max([sub_struct.(col_name).C4(:).MeanIntensity]);
    texmin_C2 = min([sub_struct.(col_name).C2(:).MeanIntensity]);
    texmin_C3 = min([sub_struct.(col_name).C3(:).MeanIntensity]);
    texmin_C4 = min([sub_struct.(col_name).C4(:).MeanIntensity]);
    t_C2max_cl = [t_C2max_cl, texmax_C2];
    t_C3max_cl = [t_C3max_cl, texmax_C3];
    t_C4max_cl = [t_C4max_cl, texmax_C4];
    C2_max = max(t_C2max_cl);
    C3_max = max(t_C3max_cl);
    C4_max = max(t_C4max_cl);
    t_C2min_cl = [t_C2min_cl, texmin_C2];
    t_C3min_cl = [t_C3min_cl, texmin_C3];
    t_C4min_cl = [t_C4min_cl, texmin_C4];
    C2_min = min(t_C2min_cl);
    C3_min = min(t_C3min_cl);
    C4_min = min(t_C4min_cl);